---
- name: install mysql
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: latest
  with_items: ['mysql-server','python-mysqldb']
- name: make sure mysql is running and enabled on startup
  service:
    name: mysql
    state: started
    enabled: yes
- name: check if my.cnf exists
  stat:
    path: "/home/{{ application.user }}/.my.cnf"
  register: my_created
- name: change the root user's password
  mysql_user:
    name: "{{ user.name }}"
    password: "{{ user.password }}"
    state: present
  with_items: "{{ users }}"
  when: not my_created.stat.exists
- name: create the my.cnf file with login credentials
  copy:
    content: 
    dest: "/{{ user.name }}/.my.cnf"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: 0600
  with_items: "{{ users }}"
  when: not my_created.stat.exists
