---
- name: install apache
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: latest
  with_items: ['apache2', 'apache2-doc', 'apache2-utils']
- name: make sure apache is running and enabled on startup
  service:
    name: apache2
    state: started
    enabled: yes
