---
- name: install git
  apt:
    name: git
    update_cache: yes
    state: latest
- name: clone the application's git repository
  git:
    repo: "{{ git.repository.application }}"
    dest: "/var/www/{{ application.name }}/"
    force: yes
- name: copy database.yml and secrets.yml
  copy:
    src: "{{ item }}"
    dest: "{{ application.base_dir }}/{{ application.name }}/config/{{ item }}"
    owner: "{{ application.user }}"
    group: "{{ application.user }}"
    mode: 0600
    force: yes
  with_items: ['database.yml', 'secrets.yml']
