---
- name: create user
  user:
    name: "{{ item.name }}"
    shell: /bin/bash
    state: present
  with_items: "{{ users }}"
- name: create sudoers file
  copy:
    content: "{{ item.name }} ALL=(ALL) NOPASSWD:ALL"
    dest: "/etc/sudoers.d/90-{{ item.name }}"
    owner: root
    group: root
    mode: 0440
  with_items: "{{ users }}"
- name: add ssh keys
  authorized_key:
    user: "{{ item.name }}"
    state: present
    key: "{{ lookup('file', item.key) }}"
  with_items: "{{ users }}"
- name: disable password authentication through ssh
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication'
    line: 'PasswordAuthentication no'
    state: present
  notify: reload ssh
- name: disable root login through ssh
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin'
    line: 'PermitRootLogin no'
    state: present
  notify: reload ssh
